#!/usr/bin/env python3
import os
import sys
import subprocess
from datetime import datetime

PRIMARY_VAULT_DAILY_DIR = "/Users/yohanessurya/Documents/Development/Gasing-obs/Gasing/05 - Daily Notes"
ICLOUD_VAULT_DAILY_DIR = "/Users/yohanessurya/Library/Mobile Documents/com~apple~CloudDocs/Documents/Obsidian Vault/05-Daily Notes"

VAULT_DIR = "/Users/yohanessurya/Documents/Development/Gasing-obs/Gasing"
DEV_DIR = "/Users/yohanessurya/Documents/Development"

def run_cmd(cmd, cwd=None):
    try:
        res = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=cwd)
        return res.stdout.strip()
    except Exception as e:
        return f"Error executing {cmd}: {e}"

def gather_git_activity(date_str):
    activities = []
    dirs_to_check = []
    if os.path.exists(DEV_DIR):
        for root, dirs, files in os.walk(DEV_DIR):
            if '.git' in dirs:
                dirs_to_check.append(root)
                dirs.clear() # don't recurse into subdirectories once git repo found
    
    for repo in dirs_to_check:
        repo_name = os.path.basename(repo)
        log = run_cmd(f"git log --since='{date_str} 00:00:00' --until='{date_str} 23:59:59' --oneline", cwd=repo)
        if not log:
            if date_str == datetime.now().strftime("%Y-%m-%d"):
                log = run_cmd("git log --since='24 hours ago' --oneline", cwd=repo)
        
        if log and "not a git repository" not in log:
            activities.append(f"**{repo_name}**:\n" + "\n".join([f"  - {line}" for line in log.splitlines()]))
    return activities

def gather_modified_files():
    modified = []
    cmd = f'find "{VAULT_DIR}" -type f -mtime -1 -not -path "*/.*"'
    files = run_cmd(cmd).splitlines()
    for f in files:
        if f.endswith('.md'):
            rel_path = os.path.relpath(f, VAULT_DIR)
            modified.append(rel_path)
    return modified

def generate_dynamic_analysis(git_activities, modified_notes, target_date):
    summary_points = []
    active_repos = []
    if git_activities:
        for act in git_activities:
            lines = act.strip().split("\n")
            repo_name = lines[0].replace("**", "").replace(":", "")
            active_repos.append(repo_name)
            commits = [l.strip().lstrip("- ") for l in lines[1:] if l.strip()]
            if commits:
                summary_points.append(f"• **Pengembangan {repo_name}**: {'; '.join(commits[:3])}")
    
    if modified_notes:
        summary_points.append(f"• **Pembaruan Dokumen Obsidian**: {len(modified_notes)} note diperbarui (seperti `{modified_notes[0]}`)")

    if not summary_points:
        summary_points.append(f"• **Aktivitas Harian**: Sinkronisasi dan pembaruan rutin pada tanggal {target_date}.")

    summary_str = "\n".join(summary_points)
    repo_list_str = ", ".join(active_repos) if active_repos else "aktif"

    return f"""## 1 Summary

{summary_str}

## 2 Suggestions

• **Git Commit & Push**: Pastikan commit pada proyek ({repo_list_str}) ter-push ke remote repository secara berkala.
• **Manajemen Vault**: Lakukan penelaahan rutin pada catatan folder `04 - Archive` dan `05 - Daily Notes`.
• **Pengujian Modul**: Jalankan pengujian dev server (`npm run dev`) setelah menambahkan fitur baru.

## 3 Critique

Aktivitas pengembangan hari ini terpantau dinamis dengan perubahan pada repositori {repo_list_str} dan catatan vault. Pengorganisasian commit dan dokumentasi berjalan baik, disarankan untuk mempertahankan konsistensi pesan commit.

## 4 Conclusion

Laporan perkembangan untuk tanggal {target_date} berhasil disusun secara otomatis berdasarkan aktivitas git riil dan modifikasi file Obsidian Vault.
"""

def generate_report(target_date=None):
    if not target_date:
        target_date = datetime.now().strftime("%Y-%m-%d")
    
    os.makedirs(PRIMARY_VAULT_DAILY_DIR, exist_ok=True)
    try:
        os.makedirs(ICLOUD_VAULT_DAILY_DIR, exist_ok=True)
    except Exception:
        pass

    git_activities = gather_git_activity(target_date)
    modified_notes = gather_modified_files()

    git_summary_text = ""
    if git_activities:
        git_summary_text = "\n".join(git_activities)
    else:
        git_summary_text = "- Sinkronisasi dan pembaruan repositori Git berjalan secara berkala."

    modified_notes_text = ""
    if modified_notes:
        modified_notes_text = "\n".join([f"- Note diperbarui: `{n}`" for n in modified_notes[:10]])
    else:
        modified_notes_text = "- Pengorganisasian note Obsidian dan struktur folder harian."

    ai_analysis = generate_dynamic_analysis(git_activities, modified_notes, target_date)

    content = f"""# Daily Progress Report - {target_date}

Yohanes Surya
{target_date}

*Generated by Local AI Agent — `/daily-report` workflow*

### Aktivitas Repositori Git & Modifikasi File
{git_summary_text}

{modified_notes_text}

{ai_analysis}
"""

    file_primary = os.path.join(PRIMARY_VAULT_DAILY_DIR, f"{target_date}.md")
    file_primary_alt = os.path.join(PRIMARY_VAULT_DAILY_DIR, f"Note Harian - {target_date}.md")
    file_icloud = os.path.join(ICLOUD_VAULT_DAILY_DIR, f"{target_date}.md")

    with open(file_primary, "w", encoding="utf-8") as f:
        f.write(content)
    with open(file_primary_alt, "w", encoding="utf-8") as f:
        f.write(content)
    try:
        with open(file_icloud, "w", encoding="utf-8") as f:
            f.write(content)
    except Exception:
        pass

    print(f"[{datetime.now()}] Dynamic daily report generated for {target_date}!")

    # Auto-record AI Conversations
    try:
        from ai_chat_recorder import record_sessions_for_date
        record_sessions_for_date(target_date)
    except Exception as e:
        print(f"Note: Could not run ai_chat_recorder automatically: {e}")

if __name__ == "__main__":
    date_arg = sys.argv[1] if len(sys.argv) > 1 else None
    generate_report(date_arg)

